### ISSUE TITLE
Increase default pagination size

### ISSUE THREAD

**Issue by toolmantim** [buildkite/buildkite-metrics#10]
With lots of agents and a few stacks, it's easy to go over 100RPM on [agents/list pagination](https://github.com/buildkite/buildkite-metrics/blob/master/main.go#L309).

We should up the page size to be 100. The default is 30.

**Comment by lox** [comment]
Sounds very sensible.

**Comment by keithpitt** [comment]
Without digging too much into the code, what data do you need from the Agents List? Is it looking for stuff on `queue=x` things?

**Comment by toolmantim** [comment]
@keithpitt it just gets the agent `meta_data` and checks if `job != nil` to see if it's "busy"

**Comment by toolmantim** [comment]
It's all the `agent.*` calls in [this code](https://github.com/buildkite/buildkite-metrics/blob/master/main.go#L336-L363)

**Comment by keithpitt** [comment]
Ah right, is there anything I could do to convince you to use the GraphQL API? :) Or would that be too hard basket? So we have queue search in the API:

```
query {
  organization() {
    agents(metaData: "queue=lol") {
      job { ... }
    }
  }
}
```

**Comment by toolmantim** [comment]
@keithpitt yeah, I don't see why not! People's API tokens would need changing tho?

We don't need to do queue search tho, we just want to grab all the agents… and then we loop through the list and collate them by queue and whether or not they have a job assigned.

**Comment by keithpitt** [comment]
I was just worried that since the Agents API endpoint has a really slow pagination mechanism, and includes _all the things_.

Ah yeah...the API tokens would need to change.

Maybe too hard basket for now...

**Comment by toolmantim** [comment]
Say you had 45 agents with 3 queues. What if we add an endpoint to the [Agents REST API](https://buildkite.com/docs/rest-api/agents)…

```bash
curl "https://api.buildkite.com/v2/organizations/{org.slug}/agents/queue-metrics"

```

which would return…

```json
{
  "count": 45,
  "busy": 20,
  "idle": 25,
  "queues": {
    "default": {
      "count": 20,
      "busy": 15,
      "idle": 5
    },
    "osx": {
      "count": 10,
      "busy": 2,
      "idle": 8
    },
    "elastic": {
      "count": 15,
      "busy": 12,
      "idle": 3
    }
  }
}
```

**Comment by keithpitt** [comment]
That could be a pretty straight forward SQL call as well - no pagination required! I'm in favour!

**Comment by lox** [comment]
I'd love this repo to not be a thing.

**Comment by lox** [comment]
I hate things.

**Comment by keithpitt** [comment]
What would it be if it wasn't a thing?!

**Comment by lox** [comment]
Yeah, fair point, unless you guys ended up pushing metrics directly into Cloudwatch it's going to stick around. I'd be perfectly happy to talk to a different less brute force endpoint or GraphQL. I tried that first, but it was very early days @keithpitt.

**Comment by keithpitt** [comment]
> ended up pushing metrics directly into Cloudwatch

That's something I've always thought would be a good future change, but I figured it'd be too hard. In saying that though, I only think it's hard mostly because I've never actually asked what it would entail!

Is it a matter of just sending queue metrics `default: 1 busy, 3 idle` type stuff to Cloudwatch?

**Comment by lox** [comment]
Yeah, probably too hard.

Providing a better API for these metrics sounds like the bigger win, or at
least exposing them via GraphQL.

**Comment by lox** [comment]
Fixed in master.
