### ISSUE TITLE
Add support for new agent metrics endpoint

### ISSUE THREAD

**Issue by toolmantim** [buildkite/buildkite-metrics#15]
There's a new endpoint available at, needing `READ_AGENTS` scope (same as the current agents polling):

    https://api.buildkite.com/v2/organizations/<org-slug>/agents/queue-metrics

It'd be good to get this beta-tested, just to see if the API is right or needs adjusting/rejigging before we publish it properly.

**Comment by lox** [comment]
Neat, will look at adding this.

**Comment by toolmantim** [comment]
```bash
$ curl -H 'Authorization: Bearer xxx' https://api.buildkite.com/v2/organizations/my-org/agents/queue-metrics
{
  "count": 50,
  "busy": 4,
  "idle": 46,
  "queues": {
    "elastic-pipeline-uploaders": {
      "count": 5,
      "busy": 0,
      "idle": 5
    },
    "docker-builder": {
      "count": 1,
      "busy": 0,
      "idle": 1
    },
    "default": {
      "count": 43,
      "busy": 3,
      "idle": 40
    },
    "elastic-builders": {
      "count": 1,
      "busy": 1,
      "idle": 0
    }
  }
}
```

**Comment by toolmantim** [comment]
A more paginatable version of this (for orgs with lots of queues) would be:

```bash
$ curl -H 'Authorization: Bearer xxx' https://api.buildkite.com/v2/organizations/my-org/agents/queue-metrics
[
  {
    "name": "elastic-pipeline-uploaders",
    "count": 5,
    "busy": 0,
    "idle": 5
  },
  {
    "name": "docker-builder",
    "count": 1,
    "busy": 0,
    "idle": 1
  },
  {
    "name": "default",
    "count": 43,
    "busy": 3,
    "idle": 40
  },
  {
    "name": "elastic-builders",
    "count": 1,
    "busy": 1,
    "idle": 0
  }
]
```

And we ditch the top-level metrics altogether. Or provide a second endpoint?

**Comment by lox** [comment]
I'm happy with just the per-queue metrics, but would LOVE it if agent-token could be used to authenticate for this API. Dropping the personal API token requirement from aws-stack would be huge.

**Comment by toolmantim** [comment]
If it uses the agent token, then perhaps it should be:

`https://agent.buildkite.com/v3/queue-metrics`

and filterable by queue for performance:

`https://agent.buildkite.com/v3/queue-metrics?queue=one,two`

How's that sound?

**Comment by lox** [comment]
Sounds amazing!

**Comment by toolmantim** [comment]
If this was built into the buildkite agent, ala `buildkite-agent queue-metrics`, then the Lambda function could just use the buildkite-agent binary and parse the JSON from STDOUT?

**Comment by lox** [comment]
Possibly, I suspect that might end up being more complicated than a
dedicated binary in practice.

**Comment by toolmantim** [comment]
Fair call.

**Comment by lox** [comment]
Any chance of this happening?! :D

**Comment by toolmantim** [comment]
Absolutely. 

The existing API endpoint is wrong, including how it figures out the "queue" for an agent (it only supports a single queue… not n queues). So that has to be fixed up first.

I'll probably get the API ready to ship around next week sometime, running from the agents API (`agent.buildkite.com`) instead of the REST API, with agent tokens as the auth.

**Comment by gugahoi** [comment]
Any updates on this? Deprecating the metrics token would be great.

**Comment by toolmantim** [comment]
It's definitely happening but no updates just yet I'm afraid.

**Comment by mdub** [comment]
Is this still on the cards (or, a card), @toolmantim?

**Comment by petemounce** [comment]
Definitely interested in this too.

A bit of context from us: we'll probably have many (hundreds) queues but only a few (low tens) actively in service. It would be convenient to be able to retrieve the metrics for "recently active" queues.

Why? We're going to use queue as our way of pinning builds to product-build-environments (that is, versions of our build agents capable of building a given product). To allow teams to decouple, in planning on running a general-purpose cluster (well, one each for Windows, macos, Linux) that ought to meet most getting-started needs, and allow teams to create their own if they need customizations (they definitely do).

Each time a new product build environment is created, it will have a unique queue name, and traffic from the previous one will drain across as it is a/b commissioned.

So, many queues, only a fraction in active service.

**Comment by lox** [comment]
This actually got implemented in https://github.com/buildkite/buildkite-metrics/pull/40!

It's currently a private API which this metrics client can access which uses the agent registration token as the credential. 

@petemounce that sounds like a really interesting approach 🤔I'd imagine you'd have an auto-scaling group for each queue? Perhaps you could query appropriately tagged auto-scaling groups to see how active they have been historically and use that as a mechanism for cleaning up unused environments?

**Comment by petemounce** [comment]
@lox yes, an autoscaling group (GCE calls those managed instance groups) per queue (per platform; each group will use the platform-specific golden image from that git sha1).

They'll be tagged, sure. However, neither cloud really offers much beyond CPU/etc metrics for busyness; this is more of an application-level concern.

I imagine I'll be able to achieve this via querying the structured logs I'll be exporting into ELK, but that will force quite a while of retention, there - not impossible, but a concern. It would be awfully convenient if this information were possible to get direct from the canonical source, rather than observation via side-effects (logs, approximations based on cloud-resource level metrics, etc).

**Comment by lox** [comment]
By business, I meant their scaling activity! E.g what is the current instance count and how long has it been since they scaled up.

**Comment by petemounce** [comment]
For other googling people, we're talking about this within https://buildkite-community.slack.com/archives/C44GER153/p1524850601000098.
