### ISSUE TITLE
-queue switch causes failure to publish metrics

### ISSUE THREAD

**Issue by gtrummell** [buildkite/buildkite-metrics#2]
Good afternoon!

I'm experimenting with both the buildkite-cloudwatch-metrics-publisher Cloudformation stack, which appears to use this tool.  I've installed both the stack, and the metrics publisher tool on my own via Google Go.  While using this publisher, I noted that the -queue switch does not work.  When using the -queue switch, even with a wide-open IAM policy, the publisher returns "Extracted 0 metrics."

**Comment by toolmantim** [comment]
Ah, sorry you're having trouble with the stack. Have you given the Buildkite API token the scopes `read_pipelines`, `read_builds` and `read_agents`? I've just updated the Readme to point this out:
https://github.com/buildkite/buildkite-metrics/commit/8b2ae0f2a76e1f1a76999b4e05f1dc8e09eadffe

**Comment by toolmantim** [comment]
I'm going to close this issue, but if you have any more information please feel free to reopen it.
