### ISSUE TITLE
AutoScaling on ScheduledJobsCount has some undesired results

### ISSUE THREAD

**Issue by yeungda-rea** [buildkite/buildkite-metrics#31]
When runnable jobs are queuing up we want to respond automatically by increasing the number of agents so that we can clear the queue. We want to match supply with demand. When jobs have been queuing up for a long period of time, we want to be paged so we can resolve the blockage.

The best indicator we have for "runnable jobs queuing up" at this time is a queue's `ScheduledJobsCount` metric. We use this for autoscaling and paging. We have recently found a couple of ways that this is not ideal. Here's a brief explanation of those scenarios:

### Limited jobs

When a job is scheduled on a queue, but unable to run because of a concurrency group, it is included in `ScheduledJobsCount`.

Since limited jobs are not runnable jobs, increasing the number of agents is the wrong response. This is what we do right now however, and we end up repeating the autoscaling of our agents until all limited jobs have been run.

### Unsatisfiable jobs

When a job is scheduled on a queue, but includes additional targeting rules that are unsatisfiable, it is included in `ScheduledJobsCount`.

Here's an example that illustrates how this happened to us this week. Someone accidentally indented  part of the step too far, which added an extra key value pair under the `agents` targeting rules: 

```yaml
steps:
  - agents:
      queue: 'deploy'
      branch: master # oops! I indented this too far
```

Since these unsatisfiable jobs are not runnable jobs, increasing the number of agents is the wrong response. These unsatisfiable jobs are also included in the `ScheduledJobsCount` metric.

Is there a better way? Is there a better metric we could create for autoscaling?

**Comment by lox** [comment]
Related https://github.com/buildkite/elastic-ci-stack-for-aws/issues/305

**Comment by lox** [comment]
Perhaps we need a way to look at the maximum age of a queued job?

**Comment by mdub** [comment]
I think we need something like `PendingJobsCount`, which _excludes_ jobs blocked on concurrency limits.

**Comment by toolmantim** [comment]
Perhaps the best fix is to simply exclude limited jobs from `ScheduledJobsCount`?

**Comment by mdub** [comment]
> Perhaps the best fix is to simply exclude limited jobs from `ScheduledJobsCount`?

That would definitely be the ideal fix for those of us using `ScheduledJobsCount` for auto-scaling; no need to modify the metrics collector, or scaling rules.

But, are there people who use that metric for other purposes, who might be inconvenienced/upset/enraged?

**Comment by toolmantim** [comment]
Good point! Hrmm… the metrics collector was designed for exactly this use case though, so I think this makes a better default.

**Comment by lox** [comment]
This was fixed with the move to the new agent metrics api in #40. Limited builds aren't counted as scheduled any more!
