### ISSUE TITLE
Add a Prometheus backend

### ISSUE THREAD

**Issue by shaneog** [buildkite/buildkite-metrics#36]
Adding a Prometheus backend would allow this to be used as a Custom Metrics autoscaling source in Kubernetes using, for example, https://github.com/directXMan12/k8s-prometheus-adapter.

**Comment by lox** [comment]
Sounds like an excellent idea!

**Comment by martinbaillie** [comment]
I'll take a look at this tomorrow

**Comment by lox** [comment]
Implemented!
