### ISSUE TITLE
Track build duration

### ISSUE THREAD

**Issue by vektah** [buildkite/buildkite-metrics#6]
It would be awesome if we could track average build duration (per pipeline?). Would be helpful for capacity planning & picking instance type.

**Comment by toolmantim** [comment]
This is coming! You've already got the basic metrics in the GraphQL API right now if you wanted to poke around…


```
query {
  pipeline(slug:"my-org/my-pipeline") {
    metrics {
      edges {
        node {
          label
          value
        }
      }
    }
  }
}
```

**Comment by eredi93** [comment]
@toolmantim @lox any plans to add this in the near future?

**Comment by petemounce** [comment]
Definitely interested in this. It would be really useful to also be able to calculate build duration estimates _per branch_, too, since we have long term support branches open concurrently, and build duration values dramatically between them.

**Comment by toolmantim** [comment]
Sorry, but I think build duration might end up out of the scope of the `buildkite-metrics` tool for a long while yet. There's nothing that can't be calculated from the REST or GraphQL APIs though, so at least there's a path forward if you need?

I might close this for now, but feel free to leave more comments as you need.

@petemounce for that level of granular data, you're definitely best to use the REST or GraphQL APIs.

**Comment by petemounce** [comment]
Would a PR adding job duration metrics by queue and job-name be welcome, if we get to this first? Promising nothing ;)

**Comment by toolmantim** [comment]
In theory yep! It's a little tricky though, because this binary uses an optimised endpoint that works off the agent token, whereas you'll need to use the REST or GraphQL API which requires an API token.

So perhaps better as a separate project, and we figure to where to go from there?

**Comment by petemounce** [comment]
Hmm, it would be more convenient to only need to run one binary...
